MAIL_USERNAME: 'arquisoftpract19@gmail.com'
MAIL_PASSWORD: 'seba19nico19pepe19' 
REDIS_USERNAME: 'user'
REDIS_PASSWORD: 'seba19nico19pepe19'
REDIS_URL: 'redis://user:seba19nico19pepe19@redis-15438.c8.us-east-1-3.ec2.cloud.redislabs.com:15438/0'